export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';

export const UPDATE_CUSTOMERS = 'UPDATE_CUSTOMERS';

export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';

export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
